kind: pipeline
name: todo

steps:
- name: build
  image: node:11
  commands:
  - yarn

- name: publish
  image: plugins/docker:latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: buglan/drone-demo
    tags: latest

- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
    host: buglan.org
    port: 28379
    user: root
    key:
      from_secret: deploy_key
    script:
    - mkidr /code
    - cd /code
    - docker pull buglan/drone-demo:latest
    - docker rm -f drone-demo
    - echo "almost done"
    - docker run --name=drone-demo -p 5000:5000 -d buglan/drone-demo
    - echo 'success'
